#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Viktor Gsteiger
url: 'http://vgsteiger.com'

description: Online Resume of Viktor Gsteiger
theme_skin: terminal
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
